"""update company with social media

Revision ID: 02e95adc94af
Revises: e95ecaa9297f
Create Date: 2026-06-22 14:29:57.870917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e95adc94af'
down_revision = 'e95ecaa9297f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('linkedin')
        batch_op.drop_column('twitter')
        batch_op.drop_column('facebook')

    # ### end Alembic commands ###
