"""update transaction

Revision ID: 040c6bb25a13
Revises: 8db10c613398
Create Date: 2026-03-22 14:05:48.766022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040c6bb25a13'
down_revision = '8db10c613398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_manager_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('buyer_manager_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('invoice_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pickup_scheduled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pickup_completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pickup_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('delivery_scheduled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivery_completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivery_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('waste_manifest_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('waste_manifest_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('weight_certificate_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('coa_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_transaction_status'), ['status'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_transaction_invoice_number'), ['invoice_number'])
        batch_op.create_foreign_key(batch_op.f('fk_transaction_seller_manager_id_user'), 'user', ['seller_manager_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_transaction_buyer_manager_id_user'), 'user', ['buyer_manager_id'], ['id'])
        batch_op.drop_column('payement_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payement_status', sa.VARCHAR(length=30), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_transaction_buyer_manager_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transaction_seller_manager_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_transaction_invoice_number'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_transaction_status'))
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('cancelled_reason')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('coa_url')
        batch_op.drop_column('weight_certificate_url')
        batch_op.drop_column('waste_manifest_url')
        batch_op.drop_column('waste_manifest_number')
        batch_op.drop_column('status')
        batch_op.drop_column('delivery_notes')
        batch_op.drop_column('delivery_completed_at')
        batch_op.drop_column('delivery_scheduled_at')
        batch_op.drop_column('pickup_notes')
        batch_op.drop_column('pickup_completed_at')
        batch_op.drop_column('pickup_scheduled_at')
        batch_op.drop_column('invoice_url')
        batch_op.drop_column('invoice_number')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('buyer_manager_id')
        batch_op.drop_column('seller_manager_id')

    # ### end Alembic commands ###
