"""update company user

Revision ID: 08d1c7138a22
Revises: 12db59a9e990
Create Date: 2026-07-04 16:12:38.410857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d1c7138a22'
down_revision = '12db59a9e990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verification_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('verification_token_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verification_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_user_email_verification_token'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_verification_token'), ['verification_token'])
        batch_op.drop_column('email_verification_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verification_token', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_user_verification_token'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_email_verification_token'), ['email_verification_token'])
        batch_op.drop_column('status')
        batch_op.drop_column('verification_attempts')
        batch_op.drop_column('verification_token_expires')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('email_verified_at')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
