"""update company documents and delete temporary subscription

Revision ID: 0d0a910333b7
Revises: 02e95adc94af
Create Date: 2026-06-23 14:16:38.735860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0a910333b7'
down_revision = '02e95adc94af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documents', sa.String(length=200), nullable=True))
        batch_op.drop_column('subscription_plan_id_temporary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan_id_temporary', sa.INTEGER(), nullable=True))
        batch_op.drop_column('documents')

    # ### end Alembic commands ###
