"""update

Revision ID: 12db59a9e990
Revises: 4c27b304f6f1
Create Date: 2026-07-04 12:33:44.837827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12db59a9e990'
down_revision = '4c27b304f6f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_attributes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_attributes', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
