"""add expired_at in item

Revision ID: 17b254a3560e
Revises: 5c7d9f114e3a
Create Date: 2026-03-21 13:39:28.038247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b254a3560e'
down_revision = '5c7d9f114e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expired_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('expired_at')

    # ### end Alembic commands ###
