"""update transaction

Revision ID: 1884de14c1e2
Revises: bcdb50c3ecbf
Create Date: 2026-03-31 22:31:10.730828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1884de14c1e2'
down_revision = 'bcdb50c3ecbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_disputed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('dispute_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dispute_raised_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dispute_raised_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('dispute_resolved_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_transaction_dispute_raised_by_user'), 'user', ['dispute_raised_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transaction_dispute_raised_by_user'), type_='foreignkey')
        batch_op.drop_column('dispute_resolved_at')
        batch_op.drop_column('dispute_raised_at')
        batch_op.drop_column('dispute_raised_by')
        batch_op.drop_column('dispute_reason')
        batch_op.drop_column('is_disputed')

    # ### end Alembic commands ###
