"""update listing

Revision ID: 19c316791b69
Revises: dd29c9925ca2
Create Date: 2026-06-21 12:17:47.974150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c316791b69'
down_revision = 'dd29c9925ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_quantity', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_column('Available_Quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Available_Quantity', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.drop_column('available_quantity')

    # ### end Alembic commands ###
