"""change to expires_at

Revision ID: 2363d4d86478
Revises: 17b254a3560e
Create Date: 2026-03-21 13:49:11.447005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2363d4d86478'
down_revision = '17b254a3560e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('expired_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expired_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
