"""update company

Revision ID: 25b319a8f12c
Revises: 8f62f9b25f3d
Create Date: 2026-04-26 16:22:28.252422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b319a8f12c'
down_revision = '8f62f9b25f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_transactions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_revenue', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('total_revenue')
        batch_op.drop_column('total_transactions')

    # ### end Alembic commands ###
