"""update company model

Revision ID: 26182d4f48d7
Revises: 6c766d74bd23
Create Date: 2026-04-09 10:24:47.391998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26182d4f48d7'
down_revision = '6c766d74bd23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('verified_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###
