"""update transaction model delivery

Revision ID: 312f7e3cef87
Revises: 0d0a910333b7
Create Date: 2026-06-28 12:15:17.386420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312f7e3cef87'
down_revision = '0d0a910333b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('dilivery_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dilivery_status', sa.VARCHAR(length=30), nullable=False))
        batch_op.drop_column('delivered_at')

    # ### end Alembic commands ###
