"""update company activity and size

Revision ID: 39ffed7d7f53
Revises: 08d1c7138a22
Create Date: 2026-07-19 10:04:55.771539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '39ffed7d7f53'
down_revision = '08d1c7138a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_company')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('business_size', sa.String(length=30), nullable=True))
        batch_op.drop_column('company_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_type', sa.VARCHAR(length=30), nullable=False))
        batch_op.drop_column('business_size')
        batch_op.drop_column('business_type')

    op.create_table('_alembic_tmp_company',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('website', sa.VARCHAR(length=200), nullable=True),
    sa.Column('logo', sa.VARCHAR(length=200), nullable=True),
    sa.Column('documents', sa.VARCHAR(length=200), nullable=True),
    sa.Column('rating_avg', sa.INTEGER(), nullable=True),
    sa.Column('total_reviews', sa.INTEGER(), nullable=True),
    sa.Column('rating_distribution', sqlite.JSON(), nullable=True),
    sa.Column('total_transactions', sa.INTEGER(), nullable=True),
    sa.Column('total_revenue', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('address', sa.VARCHAR(length=30), nullable=False),
    sa.Column('country', sa.VARCHAR(length=30), nullable=False),
    sa.Column('city', sa.VARCHAR(length=30), nullable=False),
    sa.Column('Postal_code', sa.VARCHAR(length=30), nullable=True),
    sa.Column('activity', sa.VARCHAR(length=30), nullable=False),
    sa.Column('rc', sa.VARCHAR(length=30), nullable=True),
    sa.Column('nif', sa.VARCHAR(length=30), nullable=True),
    sa.Column('nis', sa.VARCHAR(length=30), nullable=True),
    sa.Column('referal', sa.VARCHAR(length=30), nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), nullable=True),
    sa.Column('verified', sa.BOOLEAN(), nullable=True),
    sa.Column('verified_by', sa.INTEGER(), nullable=True),
    sa.Column('verified_at', sa.DATETIME(), nullable=True),
    sa.Column('facebook', sa.VARCHAR(length=30), nullable=True),
    sa.Column('twitter', sa.VARCHAR(length=30), nullable=True),
    sa.Column('linkedin', sa.VARCHAR(length=30), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('subscription_plan_id', sa.INTEGER(), nullable=True),
    sa.Column('subscription_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('subscription_started_at', sa.DATETIME(), nullable=True),
    sa.Column('subscription_ends_at', sa.DATETIME(), nullable=True),
    sa.Column('subscription_cancelled_at', sa.DATETIME(), nullable=True),
    sa.Column('subscription_grace_period_ends', sa.DATETIME(), nullable=True),
    sa.Column('subscription_grace_period_used', sa.BOOLEAN(), nullable=True),
    sa.Column('max_active_listings', sa.INTEGER(), nullable=True),
    sa.Column('max_featured_listings', sa.INTEGER(), nullable=True),
    sa.Column('max_team_members', sa.INTEGER(), nullable=True),
    sa.Column('max_monthly_transactions', sa.INTEGER(), nullable=True),
    sa.Column('commission_rate', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('auto_renew', sa.BOOLEAN(), nullable=True),
    sa.Column('stripe_customer_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('default_payment_method_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('current_listings_created', sa.INTEGER(), nullable=True),
    sa.Column('current_month_listings_created', sa.INTEGER(), nullable=True),
    sa.Column('current_month_transactions', sa.INTEGER(), nullable=True),
    sa.Column('last_reset_date', sa.DATETIME(), nullable=True),
    sa.Column('last_invoice_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('last_payment_date', sa.DATETIME(), nullable=True),
    sa.Column('last_payment_amount', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('business_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('business_size', sa.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], name=op.f('fk_company_subscription_plan_id_subscription_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company')),
    sa.UniqueConstraint('name', name=op.f('uq_company_name'))
    )
    # ### end Alembic commands ###
