"""transactions_id  for not unique in review table

Revision ID: 40d25053badc
Revises: 39ffed7d7f53
Create Date: 2026-08-08 13:44:10.218161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d25053badc'
down_revision = '39ffed7d7f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_review_transaction_id'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_review_transaction_id'), ['transaction_id'])

    # ### end Alembic commands ###
