"""update rating distribution

Revision ID: 4409d93954ae
Revises: e50a243bb61b
Create Date: 2026-06-29 00:02:57.390336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4409d93954ae'
down_revision = 'e50a243bb61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('reviewer_type')

    # ### end Alembic commands ###
