"""update code postale

Revision ID: 4ebc951c8ede
Revises: f7ef01ec9486
Create Date: 2026-05-09 19:51:54.598217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ebc951c8ede'
down_revision = 'f7ef01ec9486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Postal_code', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('Postal_code')

    # ### end Alembic commands ###
