"""update verified company to boolean

Revision ID: 58977c047f6e
Revises: 7a2152930c76
Create Date: 2026-04-08 23:37:09.722692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58977c047f6e'
down_revision = '7a2152930c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('verified',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('verified',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
