"""Initial migration with company-centric schema

Revision ID: 5c7d9f114e3a
Revises: fb69e146fb62
Create Date: 2026-03-21 02:21:16.204069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7d9f114e3a'
down_revision = 'fb69e146fb62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        batch_op.alter_column('verified',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('uri',
               existing_type=sa.VARCHAR(length=30),
               nullable='False')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_negotiable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('minimum_order', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('minimum_order')
        batch_op.drop_column('price_negotiable')

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('uri',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('verified',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.drop_column('website')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
