"""current_listings_created

Revision ID: 62926c3b8793
Revises: d6aabd7ff5b1
Create Date: 2026-06-16 20:11:01.001721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62926c3b8793'
down_revision = 'd6aabd7ff5b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_listings_created', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('current_listings_created')

    # ### end Alembic commands ###
