"""empty message

Revision ID: 6bc5b20a7e61
Revises: e2ff8f32849d
Create Date: 2026-06-09 12:15:26.166784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc5b20a7e61'
down_revision = 'e2ff8f32849d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_password_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_password_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_reset_password_token'), ['reset_password_token'], unique=True)
        batch_op.create_unique_constraint(batch_op.f('uq_user_email_verification_token'), ['email_verification_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email_verification_token'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_reset_password_token'))
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('reset_password_expires')
        batch_op.drop_column('reset_password_token')

    # ### end Alembic commands ###
