"""update verified company to boolean

Revision ID: 6c766d74bd23
Revises: f45cd6d2a85c
Create Date: 2026-04-08 23:44:53.894470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c766d74bd23'
down_revision = 'f45cd6d2a85c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_company_verified_by_user'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_company_verified_by_user'), 'user', ['verified_by'], ['id'])

    # ### end Alembic commands ###
