"""update transaction

Revision ID: 7a2152930c76
Revises: 1884de14c1e2
Create Date: 2026-04-03 13:45:56.393901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2152930c76'
down_revision = '1884de14c1e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('delivery_confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivery_confirmed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quality_accepted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('quality_accepted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('quality_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('payment_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('payment_confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_confirmed_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_transaction_payment_confirmed_by_user'), 'user', ['payment_confirmed_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_transaction_delivery_confirmed_by_user'), 'user', ['delivery_confirmed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transaction_delivery_confirmed_by_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transaction_payment_confirmed_by_user'), type_='foreignkey')
        batch_op.drop_column('payment_confirmed_by')
        batch_op.drop_column('payment_confirmed_at')
        batch_op.drop_column('payment_confirmed')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('quality_notes')
        batch_op.drop_column('quality_accepted_at')
        batch_op.drop_column('quality_accepted')
        batch_op.drop_column('delivery_confirmed_by')
        batch_op.drop_column('delivery_confirmed_at')
        batch_op.drop_column('delivery_confirmed')

    # ### end Alembic commands ###
