"""add sender_company_id

Revision ID: 8db10c613398
Revises: ba9d92a23f2c
Create Date: 2026-03-22 13:11:24.613160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db10c613398'
down_revision = 'ba9d92a23f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_offer_sender_company_id_company'), 'company', ['sender_company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_offer_sender_company_id_company'), type_='foreignkey')
        batch_op.drop_column('sender_company_id')

    # ### end Alembic commands ###
