"""update category

Revision ID: 9489cbdeb132
Revises: 1758ab452f79
Create Date: 2026-07-03 20:43:07.467257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9489cbdeb132'
down_revision = '1758ab452f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('waste_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('requires_license', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('requires_special_handling', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('min_quantity_default', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('meta_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('meta_keywords', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_category_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_slug'))
        batch_op.drop_column('meta_keywords')
        batch_op.drop_column('meta_description')
        batch_op.drop_column('meta_title')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('is_active')
        batch_op.drop_column('sort_order')
        batch_op.drop_column('min_quantity_default')
        batch_op.drop_column('requires_special_handling')
        batch_op.drop_column('requires_license')
        batch_op.drop_column('waste_type')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
