"""reverse update

Revision ID: a3f0d0b99a15
Revises: c27ad26eee90
Create Date: 2026-03-29 23:06:41.708492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f0d0b99a15'
down_revision = 'c27ad26eee90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_offer_created_by_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_offer_sender_company_id_company'), 'company', ['sender_company_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_offer_seller_id_user'), 'user', ['seller_id'], ['id'])
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('is_counter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_counter', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_offer_seller_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_offer_sender_company_id_company'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_offer_created_by_id_user'), 'user', ['created_by_id'], ['id'])
        batch_op.drop_column('seller_id')
        batch_op.drop_column('sender_company_id')

    # ### end Alembic commands ###
