"""add pickup item field

Revision ID: a82260a63142
Revises: 505aca7b59f5
Create Date: 2026-03-21 20:50:52.561860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82260a63142'
down_revision = '505aca7b59f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_address', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('pickup_city', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('pickup_country', sa.String(length=30), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=30), nullable=True))
        batch_op.drop_column('pickup_country')
        batch_op.drop_column('pickup_city')
        batch_op.drop_column('pickup_address')

    # ### end Alembic commands ###
