"""add conversation and message

Revision ID: b571334d9ce5
Revises: 6ca49293b1af
Create Date: 2026-04-27 17:05:42.583853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b571334d9ce5'
down_revision = '6ca49293b1af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('seller_deleted', sa.Boolean(), nullable=True),
    sa.Column('buyer_deleted', sa.Boolean(), nullable=True),
    sa.Column('last_message', sa.Text(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_sender_id', sa.Integer(), nullable=True),
    sa.Column('seller_unread_count', sa.Integer(), nullable=True),
    sa.Column('buyer_unread_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], name=op.f('fk_conversations_buyer_id_user')),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_conversations_item_id_item')),
    sa.ForeignKeyConstraint(['last_message_sender_id'], ['user.id'], name=op.f('fk_conversations_last_message_sender_id_user')),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], name=op.f('fk_conversations_offer_id_offer')),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], name=op.f('fk_conversations_seller_id_user')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name=op.f('fk_conversations_transaction_id_transaction')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('has_attachment', sa.Boolean(), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('attachment_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('fk_messages_sender_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('conversations')
    # ### end Alembic commands ###
