"""update category

Revision ID: ba9caf469a93
Revises: 9489cbdeb132
Create Date: 2026-07-03 21:08:15.697357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9caf469a93'
down_revision = '9489cbdeb132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_category_parent_id_category'), 'category', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_category_parent_id_category'), type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
