"""add is counter for counter offer

Revision ID: bcdb50c3ecbf
Revises: a3f0d0b99a15
Create Date: 2026-03-29 23:40:24.562908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcdb50c3ecbf'
down_revision = 'a3f0d0b99a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_offer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_counter', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_offer_parent_offer_id_offer'), 'offer', ['parent_offer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_offer_parent_offer_id_offer'), type_='foreignkey')
        batch_op.drop_column('is_counter')
        batch_op.drop_column('parent_offer_id')

    # ### end Alembic commands ###
