"""adding totale_reviews and logo to company

Revision ID: bf2359361a1d
Revises: 6fb3ed49dfd2
Create Date: 2026-03-27 22:08:16.637350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2359361a1d'
down_revision = '6fb3ed49dfd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('total_reviews', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('total_reviews')
        batch_op.drop_column('logo')

    # ### end Alembic commands ###
