"""update offer by changing sender to created_by

Revision ID: c27ad26eee90
Revises: d24cda83efd3
Create Date: 2026-03-29 22:57:27.138164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c27ad26eee90'
down_revision = 'd24cda83efd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_counter', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_offer_sender_company_id_company'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_offer_seller_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_offer_created_by_id_user'), 'user', ['created_by_id'], ['id'])
        batch_op.drop_column('sender_company_id')
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('sender_company_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_offer_created_by_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_offer_seller_id_user'), 'user', ['seller_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_offer_sender_company_id_company'), 'company', ['sender_company_id'], ['id'])
        batch_op.drop_column('is_counter')
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###
