"""add  requires_delivery and delivery_address

Revision ID: d24cda83efd3
Revises: 95a6f9633b33
Create Date: 2026-03-28 13:50:51.507538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24cda83efd3'
down_revision = '95a6f9633b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_delivery', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('delivery_address', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('requires_delivery')

    # ### end Alembic commands ###
