"""add grace periode

Revision ID: d6aabd7ff5b1
Revises: 6bc5b20a7e61
Create Date: 2026-06-14 14:24:34.733489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6aabd7ff5b1'
down_revision = '6bc5b20a7e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_grace_period_ends', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('subscription_grace_period_used', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('subscription_grace_period_used')
        batch_op.drop_column('subscription_grace_period_ends')

    # ### end Alembic commands ###
