"""update category

Revision ID: db8e9f6372cc
Revises: ba9caf469a93
Create Date: 2026-07-04 00:04:01.329433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8e9f6372cc'
down_revision = 'ba9caf469a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_category')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=300), nullable=True))
        batch_op.drop_column('Description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Description', sa.VARCHAR(length=300), nullable=False))
        batch_op.drop_column('description')

    op.create_table('_alembic_tmp_category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('default_image_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=100), nullable=True),
    sa.Column('waste_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('requires_license', sa.BOOLEAN(), nullable=True),
    sa.Column('requires_special_handling', sa.BOOLEAN(), nullable=True),
    sa.Column('min_quantity_default', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), nullable=True),
    sa.Column('meta_title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('meta_description', sa.TEXT(), nullable=True),
    sa.Column('meta_keywords', sa.VARCHAR(length=200), nullable=True),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=300), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], name=op.f('fk_category_parent_id_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    # ### end Alembic commands ###
