"""update listing

Revision ID: dd29c9925ca2
Revises: bdaf09aa29e2
Create Date: 2026-06-21 12:10:33.556040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd29c9925ca2'
down_revision = 'bdaf09aa29e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Available_Quantity', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sold_quantity', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('sold_quantity')
        batch_op.drop_column('Available_Quantity')

    # ### end Alembic commands ###
