"""subscription plan id temporary for pending payement

Revision ID: e2ff8f32849d
Revises: cc89d3a1d413
Create Date: 2026-06-02 12:20:12.460514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ff8f32849d'
down_revision = 'cc89d3a1d413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan_id_temporary', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('subscription_plan_id_temporary')

    # ### end Alembic commands ###
