"""update rating distribution

Revision ID: e50a243bb61b
Revises: b64e79fd8df6
Create Date: 2026-06-28 22:40:59.411472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e50a243bb61b'
down_revision = 'b64e79fd8df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_distribution', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('rating_distribution')

    # ### end Alembic commands ###
