"""update user

Revision ID: e95ecaa9297f
Revises: 6b732e0f89ae
Create Date: 2026-06-21 16:23:24.714305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95ecaa9297f'
down_revision = '6b732e0f89ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('notification_preferences', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notification_preferences')
        batch_op.drop_column('department')
        batch_op.drop_column('job_title')

    # ### end Alembic commands ###
