"""update verified company 

Revision ID: f45cd6d2a85c
Revises: 58977c047f6e
Create Date: 2026-04-08 23:41:45.500255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45cd6d2a85c'
down_revision = '58977c047f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_company_verified_by_user'), 'user', ['verified_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_company_verified_by_user'), type_='foreignkey')
        batch_op.drop_column('verified_by')

    # ### end Alembic commands ###
