"""add subscription

Revision ID: f7ef01ec9486
Revises: b571334d9ce5
Create Date: 2026-04-28 15:08:23.447489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ef01ec9486'
down_revision = 'b571334d9ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_yearly', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('stripe_price_id_monthly', sa.String(length=100), nullable=True),
    sa.Column('stripe_price_id_yearly', sa.String(length=100), nullable=True),
    sa.Column('stripe_product_id', sa.String(length=100), nullable=True),
    sa.Column('max_active_listings', sa.Integer(), nullable=True),
    sa.Column('max_featured_listings', sa.Integer(), nullable=True),
    sa.Column('max_team_members', sa.Integer(), nullable=True),
    sa.Column('max_monthly_transactions', sa.Integer(), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('has_analytics', sa.Boolean(), nullable=True),
    sa.Column('has_api_access', sa.Boolean(), nullable=True),
    sa.Column('has_priority_support', sa.Boolean(), nullable=True),
    sa.Column('has_bulk_upload', sa.Boolean(), nullable=True),
    sa.Column('has_advanced_filters', sa.Boolean(), nullable=True),
    sa.Column('has_dedicated_manager', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=True),
    sa.Column('features_list', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans')),
    sa.UniqueConstraint('slug', name=op.f('uq_subscription_plans_slug'))
    )
    op.create_table('subscription_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('interval', sa.String(length=10), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_url', sa.String(length=500), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_method_details', sa.JSON(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(length=100), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_subscription_payments_company_id_company')),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], name=op.f('fk_subscription_payments_subscription_plan_id_subscription_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_payments')),
    sa.UniqueConstraint('invoice_number', name=op.f('uq_subscription_payments_invoice_number'))
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('subscription_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('subscription_ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('subscription_cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('max_active_listings', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_featured_listings', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_team_members', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_monthly_transactions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('auto_renew', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('default_payment_method_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('current_month_listings_created', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_month_transactions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_reset_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_invoice_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('last_payment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_payment_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_company_subscription_plan_id_subscription_plans'), 'subscription_plans', ['subscription_plan_id'], ['id'])

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('featured_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('boost_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('boost_score')
        batch_op.drop_column('featured_expires_at')
        batch_op.drop_column('is_featured')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_company_subscription_plan_id_subscription_plans'), type_='foreignkey')
        batch_op.drop_column('last_payment_amount')
        batch_op.drop_column('last_payment_date')
        batch_op.drop_column('last_invoice_url')
        batch_op.drop_column('last_reset_date')
        batch_op.drop_column('current_month_transactions')
        batch_op.drop_column('current_month_listings_created')
        batch_op.drop_column('default_payment_method_id')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('auto_renew')
        batch_op.drop_column('commission_rate')
        batch_op.drop_column('max_monthly_transactions')
        batch_op.drop_column('max_team_members')
        batch_op.drop_column('max_featured_listings')
        batch_op.drop_column('max_active_listings')
        batch_op.drop_column('subscription_cancelled_at')
        batch_op.drop_column('subscription_ends_at')
        batch_op.drop_column('subscription_started_at')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('subscription_plan_id')

    op.drop_table('subscription_payments')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
