"""update offer by adding expired_at, responded_at

Revision ID: fafae3809c8a
Revises: 9af8e25d4024
Create Date: 2026-03-27 16:10:45.495699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fafae3809c8a'
down_revision = '9af8e25d4024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('responded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_column('responded_at')
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
