"""Add option_id column to quality_listing model

Revision ID: fb69e146fb62
Revises: 
Create Date: 2026-03-10 23:26:07.059491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb69e146fb62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('uri',
               existing_type=sa.VARCHAR(length=30),
               nullable='False')

    with op.batch_alter_table('item_quality_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'quality_attribute_options', ['option_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_quality_values', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('option_id')

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('uri',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###
